import = [
    "~/.config/alacritty/themes/nord.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "OnlyCopy"

[window]
padding = { x = 4, y = 4 }
# Only needed on MacOS
option_as_alt = "Both"

[font]
size = 17.0
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }

[cursor]
style = { shape = "Block" }
thickness = 1.0
