# JetBrains Darcula Alacritty Colors
# Default colors
[colors.primary]
background = '#2b2b2b'
foreground = '#a9b7c6'

# Normal colors
[colors.normal]
black = '#2b2b2b'
red = '#ff6b68'
green = '#a8c023'
yellow = '#d6bf55'
blue = '#5394ec'
magenta = '#ae8abe'
cyan = '#299999'
white = '#a9b7c6'

# Bright colors
[colors.bright]
black = '#606366'
red = '#ff8785'
green = '#c7df5b'
yellow = '#ffd866'
blue = '#7eaef1'
magenta = '#c9abca'
cyan = '#4eb4b4'
white = '#ffffff'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#cc7832'

[[colors.indexed_colors]]
index = 17
color = '#ffc66d'
